language: node_js

node_js:
- '12'

deploy:
  provider: npm
  skip_cleanup: true
  email: "loica.marotte@gmail.com"
  api_key: $NPM_TOKEN

before_install:
  - sudo apt update
  - sudo apt install ffmpeg
  - ffmpeg -version
